### ISSUE TITLE
Possibility to drive with PWM?

### ISSUE THREAD

**Issue by TechOverflow** [Infineon/PROFET-2-12V-Arduino-Shield#2]
Hi, is it possible to drive these FETs with PWM?
If so, anything to consider?
Thanks!

**Comment by IFXGAWU** [comment]
Hi, PWM is possible. Typical PWM frequencies are ~ 400Hz. Please consider sensing delays and the max. output slew rate of the device which you can find in the datasheet. BR

**Comment by ederjc** [comment]
Thanks for replying, @IFXGAWU! I close this issue as completed.
